# Generated by Django 3.2.3 on 2021-06-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': 'Navbar', 'verbose_name_plural': 'Navbar'},
        ),
        migrations.AlterField(
            model_name='navbar',
            name='bg_color',
            field=models.CharField(default='rgb(255, 255, 255, .5)', max_length=30),
        ),
    ]
